apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoder
  namespace: default
  labels:
    app: decoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decoder
  template:
    metadata:
      labels:
        app: decoder
    spec:
      containers:
        - name: decoder
          image: docker.io/vhiveease/video-analytics-decoder:latest
          imagePullPolicy: Always
          args: ["-addr", "recog.default.svc.cluster.local:80"]
          resources:
            requests:
              cpu: "250m"
              memory: "1024Mi"
            limits:
              cpu: "200000m"
              memory: "12800Mi"
          env:
            - name: TRANSFER_TYPE
              value: "INLINE"
            - name: DecoderFrames
              value: "1"
            - name: CONCURRENT_RECOG
              value: "true"
            - name: MAX_DECODER_SERVER_THREADS
              value: "10"
            - name: ENABLE_TRACING
              value: "false"
          ports:
            # For `h2c`, see https://knative.tips/networking/http2/
            - name: h2c
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: decoder
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: decoder
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: decoder-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: decoder
  minReplicas: 1
  maxReplicas: 1000
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80