apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoder
  namespace: default
  labels:
    app: decoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decoder
  template:
    metadata:
      labels:
        app: decoder
    spec:
      containers:
        - name: decoder
          image: docker.io/vhiveease/video-analytics-decoder:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 20Mi
              cpu: 250m
            limits:
              memory: 20Mi
              cpu: 250m
          args: ["-addr", "recog.default.svc.cluster.local:80"]
          env:
            - name: TRANSFER_TYPE
              value: "INLINE"
            - name: DecoderFrames
              value: "1"
            - name: CONCURRENT_RECOG
              value: "true"
            - name: MAX_DECODER_SERVER_THREADS
              value: "10"
            - name: ENABLE_TRACING
              value: "false"
          ports:
            # For `h2c`, see https://knative.tips/networking/http2/
            - name: h2c
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: decoder
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: decoder
  ports:
  - port: 80
    targetPort: 80