apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fibonacci-python-xjfciqlcbh
  name: fibonacci-python-xjfciqlcbh
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci-python-xjfciqlcbh
  template:
    metadata:
      labels:
        app: fibonacci-python-xjfciqlcbh
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node-1.alan.ragger-pg0.utah.cloudlab.us
      containers:
      - args:
        - --addr=0.0.0.0:50000
        - --function-endpoint-url=0.0.0.0
        - --function-endpoint-port=50051
        - --function-name=fibonacci-python
        - --value=10
        - --generator=linear
        - --lowerBound=1
        - --upperBound=10
        image: docker.io/vhiveease/relay:latest
        name: relay
        ports:
        - containerPort: 50000
          name: h2c
        resources:
          limits:
            cpu: 1000m
            memory: 8192Mi
          requests:
            cpu: 60m
            memory: 64Mi
      - args:
        - --addr=0.0.0.0
        - --port=50051
        image: docker.io/vhiveease/fibonacci-python:latest
        name: fibonacci-python-xjfciqlcbh
        resources:
          limits:
            cpu: 1000m
            memory: 8192Mi
          requests:
            cpu: 60m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci-python-xjfciqlcbh
  namespace: default
spec:
  ports:
  - port: 50000
    targetPort: 50000
  selector:
    app: fibonacci-python-xjfciqlcbh
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fibonacci-python-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fibonacci-python
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80