apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fibonacci-python-2
  name: fibonacci-python-2-xdpjbwviml
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci-python-2
  template:
    metadata:
      labels:
        app: fibonacci-python-2
    spec:
      containers:
      - args:
        - --addr=0.0.0.0:50000
        - --function-endpoint-url=0.0.0.0
        - --function-endpoint-port=50051
        - --function-name=fibonacci-python
        - --value=10
        - --generator=linear
        - --lowerBound=1
        - --upperBound=10
        image: docker.io/vhiveease/relay:latest
        name: relay
        ports:
        - containerPort: 50000
          name: h2c
        resources:
          limits:
            cpu: 200000m
            memory: 12800Mi
          requests:
            cpu: 250m
            memory: 1024Mi
      - args:
        - --addr=0.0.0.0
        - --port=50051
        image: docker.io/vhiveease/fibonacci-python:latest
        name: fibonacci-python-2-xdpjbwviml
        resources:
          limits:
            cpu: 200000m
            memory: 12800Mi
          requests:
            cpu: 250m
            memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci-python-2
  namespace: default
spec:
  ports:
  - port: 50000
    targetPort: 50000
  selector:
    app: fibonacci-python-2
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fibonacci-python-2-xdpjbwviml
spec:
  maxReplicas: 1000
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fibonacci-python-2-xdpjbwviml
