apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-app-user
  namespace: default
  labels:
    app: hotel-app-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-app-user
  template:
    metadata:
      labels:
        app: hotel-app-user
    spec:
      containers:
        # Relay --------------
        - name: relay
          image: docker.io/vhiveease/relay:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=8083
            - --function-name=user
            - --value=hello
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"

        # Function ------------
        - name: function
          image: docker.io/vhiveease/hotel-app-user:latest
          args:
            - --url=0.0.0.0
            - --port=8083
            - --db_addr=hotel-app-database:27017
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-app-user
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: hotel-app-user
  ports:
  - port: 50000
    targetPort: 50000