apiVersion: v1
kind: Service
metadata:
  name: hotel-app-recommendation
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: hotel-app-recommendation
  ports:
  - port: 50000
    targetPort: 50000