apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-app-geo
  namespace: default
  labels:
    app: hotel-app-geo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-app-geo
  template:
    metadata:
      labels:
        app: hotel-app-geo
    spec:
      containers:
        # Relay --------------
        - name: relay
          image: docker.io/vhiveease/relay:latest
          ports:
          resources:
            requests:
              memory: 20Mi
              cpu: 250m
            limits:
              memory: 20Mi
              cpu: 250m
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=8083
            - --function-name=geo

        # Function ------------
        - name: function
          image: docker.io/vhiveease/hotel-app-geo:latest
          resources:
            requests:
              memory: "20Mi"
              cpu: "250m"
            limits:
              memory: "20Mi"
              cpu: "250m"
          args:
            - --url=0.0.0.0
            - --port=8083
            - --db_addr=hotel-app-database:27017
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-app-geo
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: hotel-app-geo
  ports:
  - port: 50000
    targetPort: 50000