apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-app-profile
  namespace: default
  labels:
    app: hotel-app-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-app-profile
  template:
    metadata:
      labels:
        app: hotel-app-profile
    spec:
      containers:
        # Relay --------------
        - name: relay
          image: docker.io/vhiveease/relay:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=8083
            - --function-name=profile
            - --value="2,12,21"
          resources:
            requests:
              cpu: "250m"
              memory: "1024Mi"
            limits:
              cpu: "1000m"
              memory: "8192Mi"

        # Function ------------
        - name: function
          image: docker.io/vhiveease/hotel-app-profile:latest
          args:
            - --url=0.0.0.0
            - --port=8083
            - --db_addr=hotel-app-database:27017
            - --memcached_addr=hotel-app-mmc:11211
          resources:
            requests:
              cpu: "250m"
              memory: "1024Mi"
            limits:
              cpu: "1000m"
              memory: "8192Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-app-profile
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: hotel-app-profile
  ports:
  - port: 50000
    targetPort: 50000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotel-app-profile-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hotel-app-profile
  minReplicas: 1
  maxReplicas: 1000
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80