apiVersion: apps/v1
kind: Deployment
metadata:
  name: recog
  namespace: default
  labels:
    app: recog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recog
  template:
    metadata:
      labels:
        app: recog
    spec:
      containers:
        - name: recog
          image: docker.io/vhiveease/video-analytics-recog:latest
          imagePullPolicy: Always
          env:
            - name: TRANSFER_TYPE
              value: "INLINE"
            - name: MAX_RECOG_SERVER_THREADS
              value: "10"
            - name: ENABLE_TRACING
              value: "false"
          args: []
          resources:
            requests:
              cpu: "250m"
              memory: "1024Mi"
            limits:
              cpu: "1000m"
              memory: "8192Mi"
          ports:
            # For `h2c`, see https://knative.tips/networking/http2/
            - name: h2c
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: recog
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: recog
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recog-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recog
  minReplicas: 1
  maxReplicas: 1000
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80