apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hotel-app-geo-tracing
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "<placeholder>"
        autoscaling.knative.dev/max-scale: "<placeholder>"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - <placeholder>
      containers:
        # Relay --------------
        - name: relay
          image: docker.io/vhiveease/relay:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=8083
            - --function-name=geo
          env:
            - name: ENABLE_TRACING
              value: "true"

        # Function ------------
        - name: function
          image: docker.io/vhiveease/hotel-app-geo:latest
          args:
            - --url=0.0.0.0
            - --port=8083
            - --db_addr=hotel-app-database:27017
          env:
            - name: ENABLE_TRACING
              value: "true"
