apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "<placeholder>"
        autoscaling.knative.dev/max-scale: "<placeholder>"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - <placeholder>
      containers:
        # Relay ---
        - name: relay
          image: docker.io/vhiveease/relay:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=3550
            - --function-name=productcatalogservice
            - --generator=unique
            - --value=loremipsum
            - --function-method=ListProducts
        # Function ---
        - name: function
          image: docker.io/vhiveease/onlineshop-productcatalogservice:latest
          env:
          - name: PORT
            value: "3550"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
