apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: shippingservice
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "<placeholder>"
        autoscaling.knative.dev/max-scale: "<placeholder>"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - <placeholder>
      containers:
        # Relay ---
        - name: relay
          image: docker.io/vhiveease/relay:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=50051
            - --function-name=shippingservice
            - --generator=unique
            - --function-method=ShipOrder
        # Function ---
        - name: function
          image: docker.io/vhiveease/onlineshop-shippingservice:latest
          env:
          - name: PORT
            value: "50051"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
