apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci-python
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "<placeholder>"
        autoscaling.knative.dev/max-scale: "<placeholder>"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - <placeholder>
      containers:
        - image: docker.io/vhiveease/relay:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=50051
            - --function-name=fibonacci-python
            - --value=10
            - --generator=linear
            - --lowerBound=1
            - --upperBound=10
        - image: docker.io/vhiveease/fibonacci-python:latest
          args:
            - --addr=0.0.0.0
            - --port=50051