wandb_version: 1

benchmark:
  desc: null
  value: fibonacci-python
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692213610.524376
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.15.8
      8:
      - 5
